lib/src/core_matchers.dart
=> core-matchers: remove the name parameter from isInstanceOf's constructor

CHANGELOG.md, lib/src/iterable_matchers.dart, pubspec.yaml, test/iterable_matchers_test.dart
This matcher is useful for testing that expected values are present
while allowing for additional values, or when used multiple times for
testing the combination of multiple ordered collections while allowing
for aribtrary interleaving.
=> Add containsAllInOrder

lib/src/core_matchers.dart, test/string_matchers_test.dart
It was eating rest of description when nested in other Matchers
=> StringEqualsMatcher adds to mismatchDescription instead of replace mismatchDescription

lib/src/util.dart
The predicate case in wrapMatcher is essentially relying on a now deprecated feature of strong mode that treated `dynamic` as `bottom` when used in a function argument position.  This feature is being deprecated and removed in Dart 2.0 (more context here https://github.com/dart-lang/sdk/issues/29630 ).  
This adds code to explicitly handle the cases previously handled using fuzzy arrows.
=> Change wrapMatcher to avoid relying on fuzzy arrows

CHANGELOG.md, lib/src/core_matchers.dart, lib/src/iterable_matchers.dart, lib/src/numeric_matchers.dart, lib/src/string_matchers.dart, pubspec.yaml
Sorry for the second PR in a row.   This is part of the continuing effort to eliminate fuzzy arrows:  https://github.com/dart-lang/sdk/issues/29630 .
This PR isn't required for the effort, but it is intended to make the API friendlier to typed code, so that fewer changes are required in user code.  I noticed when working on other code that calls to `predicate` cause frequent error messages about fuzzy arrows.  The only two API facing changes are to `predicate` and `pairWiseCompare`.  In both cases, I am proposing to make those functions generic, so that their function argument can be typed precisely.  This is so that code that looks like:
```dart
predicate((List<int> x) => x[0] = 1);
```
will be strong mode clean, instead of having to be written as:
```dart
predicate((_x) {List<int> x = …
```
=> Strong mode fixes

pubspec.yaml
No longer needed with current design. Blocks `pub get` from edge builds
=> Remove -dev.infinity from SDK constraint

CHANGELOG.md, lib/src/iterable_matchers.dart, pubspec.yaml, test/iterable_matchers_test.dart
Fixes #73
Reimplements the unordered matcher using a recursive search assuming
that matchers can match multiple values in the input rather than a
greedy algorithm which allows a matcher to "consume" a value that is
needed for some other matcher.
User visible differences:
- May match inputs that would have previously been (incorrectly)
rejected.
- The failure description no longer includes the index of the matcher
which is unmatched, and all unmatched matchers are printed rather than
the first.
=> Fix unorderedMatches for poorly ordered input

CHANGELOG.md, lib/src/iterable_matchers.dart, pubspec.yaml, test/iterable_matchers_test.dart
Closes #72
- Add `mustMatchEveryValue` to the implementation for unordered matches.
- Implement containsAll as an unorderedMatches which does allows extra
values in the checked iterable.
=> Add containsAll

test/pretty_print_test.dart
Fixes #79 
The `toString()` changes depending on whether the VM is running with
Dart 2 semantics.
=> Fix pretty print test in Dart 2 mode

lib/src/pretty_print.dart, test/pretty_print_test.dart
Fixes prettyPrint function and associated test
Follow-up to https://github.com/dart-lang/matcher/commit/d947ffb7070f7acfa4b6e92c5f42dcd568ca245a
=> fix: prettyPrint for instance of `Type` is not an instance of the Type

lib/src/interfaces.dart
Description: break out a single-sentence summary
Macher:
- break out a single-sentence summary for class and functions
- Append a note to the top of the functions that they are meant for
subclasses, not end users – helpful in the 90% case of folks scanning
the API docs
=> misc(docs): Improve the documentation on Description and Matcher

CHANGELOG.md, lib/matcher.dart, lib/src/core_matchers.dart, lib/src/error_matchers.dart, lib/src/having_matcher.dart, lib/src/type_matcher.dart, test/core_matchers_test.dart, test/having_test.dart, test/type_matcher_test.dart
`TypeMatcher`
- No longer abstract
- Added type argument
- Deprecate the existing `name` parameter, tell folks to the type param
- Added `having` method which allows chained validation of features
- Eliminated 13 private implementations from the package
- Just use it directly.
- Moved to its own file
Deprecate `isInstanceOf` class.
- Tell folks to use `TypeMatcher<T>` instead
- Run away from weirdly named classes
Tests
- centralizing tests in type_matcher_test
- Removed isInstanceOf tests from core_matchers_test
=> feature: Upgrade TypeMatcher, deprecate isInstanceOf

CHANGELOG.md, lib/src/core_matchers.dart, lib/src/equals_matcher.dart, lib/src/feature_matcher.dart, lib/src/iterable_matchers.dart, lib/src/numeric_matchers.dart, lib/src/string_matchers.dart, test/core_matchers_test.dart, test/iterable_matchers_test.dart, test/numeric_matchers_test.dart, test/pretty_print_test.dart, test/string_matchers_test.dart, test/test_utils.dart
- Add a new TypedMatcher class to generalize `matches` type checking
- Use TypeMatcher across many of the existing Matcher implementations
- Update tests validate new, more consistent failure messages
- Add a few new tests for `isIn`
=> fix: Improve the output of many matchers that expect specific types

lib/src/custom_matcher.dart, test/custom_matcher_test.dart
- Encourages the avoidance of dynamic method calls.
- Fixes #101.
=> Update CustomMatcher example and test to use cast to Widget.

analysis_options.yaml, lib/src/type_matcher.dart, test/type_matcher_test.dart
The name of the error reported in the latest SDK changed.
Also ignore todos so it's easy to see when the analysis list is clean.
=> Fix ignores for deprecated member usage

CHANGELOG.md, lib/src/core_matchers.dart, lib/src/type_matcher.dart, test/type_matcher_test.dart
Closes #103
Closes #98
`isA` is a shorter name that reads just as nicely as `isInstanceOf` and
gives a path for an incremental migration to using a method instead of a
class.
=> Add `isA<T>()` to create TypeMatcher instances

.travis.yml, CHANGELOG.md, README.md, analysis_options.yaml, codereview.settings, lib/src/equals_matcher.dart, lib/src/iterable_matchers.dart, lib/src/pretty_print.dart, pubspec.yaml
- test on oldest support Dart SDK
- remove unneeded codereview.settings
- Fix latest pedantic lints
- Add prefer_generic_function_type_aliases
- Remove deprecated super_goes_last
- Ignore prefer_collection_literals – waiting until min SDK is 2.2
=> Fixes for analysis and Travis

CHANGELOG.md, lib/src/pretty_print.dart, test/pretty_print_test.dart
Fixes #115
The default print of `"?"` for private implementation classes can be
confusing, especially cases like `[Uri.parse('')]` which pretty prints
as `[?:]`.
- Add more types to print like "primitives" where they already include
the type name in their default `toString`.
- Remove handling of `null`, it is handled already in the calling
function.
- Add handling for some core types that are backed by private
implementation classes.
- Remove the unnecessary try/catch and outdated comments.
=> Allow private types in pretty print

.travis.yml, lib/src/core_matchers.dart, lib/src/equals_matcher.dart, lib/src/having_matcher.dart, lib/src/iterable_matchers.dart, lib/src/numeric_matchers.dart, lib/src/pretty_print.dart, lib/src/string_matchers.dart, lib/src/type_matcher.dart, lib/src/util.dart, pubspec.yaml, test/core_matchers_test.dart, test/custom_matcher_test.dart, test/escape_test.dart, test/having_test.dart, test/iterable_matchers_test.dart, test/numeric_matchers_test.dart, test/operator_matchers_test.dart, test/order_matchers_test.dart, test/pretty_print_test.dart, test/string_matchers_test.dart
- prefer_single_quotes
- prefer_spread_collections
- unused_field
- use_function_type_syntax_for_parameters
Bump min sdk to 2.3.0 to allow for spreads in collection literals.
Drop unused author field from pubspec.
=> Fix newly enforced package:pedantic lints

.travis.yml, CHANGELOG.md, pubspec.yaml
Update dependency overrides to get the latest version of test(_*) pkgs
=> Update SDK constraint to require Dart 2.4

lib/src/error_matchers.dart, test/type_matcher_test.dart
For consistency with the SDK, and in anticipation of all `is*Error`
matchers being deprecated in some future release, eagerly deprecate
`isCastError`.
=> Deprecate isCastError

test/having_test.dart
Background: https://dart-review.googlesource.com/c/sdk/+/146024
The above change breaks package:matcher tests.  Adjust the failure
test to stop caring about an exact error message.
I also considered a much simpler change to make the test check for
both old and new versions of the RangeError message, but:
* If the RangeError message changes again, I'd prefer to avoid
dealing with this again.
* From a code-coverage standpoint, it's harder to verify that
multiple versions of the message are correct.
=> Make tests tolerate the new RangeError message

CHANGELOG.md, lib/src/type_matcher.dart, pubspec.yaml, test/type_matcher_test.dart
This allows testing utilities that operate on matchers to provide
descriptive errors when TypeMatcher does not match.
Fixes #145
=> Implement describeMismatch for TypeMatcher.

CHANGELOG.md, lib/src/equals_matcher.dart, pubspec.yaml, test/core_matchers_test.dart, test/having_test.dart, test/iterable_matchers_test.dart
Previously, if the user tried to do a deep match where the expectation
included a complex matcher (such as a "having" matcher), the failure
message would just say "failed to match ..."; it wouldn't call on the
expectation's matcher to explain why the match failed.
`_DeepMatcher` now stores a `_Mismatch` object in the matchState
map (under the key `mismatch`) recording in detail the location
of the mismatch, the actual and expected values, and if
necessary, a callback that describes the problem in more detail.
This replaces the old `reason` object, which was a String.  Using
a `_Mismatch` object allows us to pass the `verbose` flag through
when calling on the inner expectation's matcher to explain why
the match failed.  It also avoids unnecessary string operations
if no description is …
=> Rework _DeepMatcher so that it can display details of match failures.

.travis.yml, pubspec.yaml
Add `test_api` and `test_core` to `dev_dependencies` in addition to
`dependency_overrides`. This prevents a warning on publish about
overriding non-dev dependencies.
Use `any` constraints` for the `dev_dependencies` since they are already
constrained correctly by `dependency_overrides`.
=> Update to latest test_* deps

lib/src/util.dart, test/core_matchers_test.dart
The check against `_Predicate<Object>` was intended to be a top type,
but the migration didn't add a `?` so the static type at the call to
`predicate(x)` was `predicate<Object>(x)`. The predicate matcher first
does a type check against it's `T` when matching values, and `null is
Object` returns `false` in an opt-in library. The effect is that a
`Function(dynamic)` gets unnecessarily limited to a `Function(Object)`
and the type check is done artificially by the matcher instead of by the
function itself.
Check against `Object?` instead to make it a null safe top type. Add a
regression test that fails before the fix is applied.
=> Allow wrapping predicates which take dynamic

test/core_matchers_test.dart, test/pretty_print_test.dart, test/test_utils.dart
These tests have not been run with a Dart 1 SDK for a long time, there
is no need to have conditional gates around legacy behavior.
=> Drop Dart 1 test code

lib/src/util.dart, test/core_matchers_test.dart
In legacy Dart `Null` is a bottom type, so checking against
`Function(Null)` is an arity check. In null safe Dart the only bottom
type is `Never`. Without this fix when running with
`--enable-experiment=non-nullable` and a predicate callback with an
argument type other than `dynamic` or `Object?` the matcher wrapping
would fall through to use `equals` instead of wrapping as a predicate.
Add a regression test that previously fails as long as the test is run
with the experiment enabled. Without the experiment (or when running
with a predicate from opt-out code) the wrapping continued to work.
=> Fix check for predicate with typed argument

analysis_options.yaml, lib/src/util.dart
This shares the same name as the class in a different library which
makes it confusing. Private typedefs go against best practices and the
inline function types are more readable than trying to figure out what
the generic means.
=> Remove private _Predicate typedef

lib/mirror_matchers.dart, lib/src/core_matchers.dart, lib/src/custom_matcher.dart, lib/src/description.dart, lib/src/equals_matcher.dart, lib/src/feature_matcher.dart, lib/src/having_matcher.dart, lib/src/interfaces.dart, lib/src/iterable_matchers.dart, lib/src/map_matchers.dart, lib/src/operator_matchers.dart, lib/src/order_matchers.dart, lib/src/pretty_print.dart, lib/src/string_matchers.dart, lib/src/util.dart, test/custom_matcher_test.dart, test/having_test.dart, test/test_utils.dart
Find parameters that are implicitly `dynamic` and add a static type of
either `Object?` or in some cases where a non-null value was clearly
required `Object`. There may be missed cases where a non-null value is
required.
Add `as dynamic` casts back in places where we were already relying on
dynamic calls as required to pass static analysis. This has the added
benefit of making those dangerous calls more obvious.
=> Add types to more parameters

lib/src/interfaces.dart
This argument had been implicitly dynamic. #162 made it `Object?` which
can cause analysis errors that are otherwise hidden due to implicit
casts. Any classes which implement `Matcher` and override `match` could
omit the argument type, which inherits from the parent. When that
became `Object?` the cast to some other type coming from `dynamic`
must now be explicit.
=> Make the item argument to Match dynamic again

lib/src/custom_matcher.dart
Similar to #163 changing the argument type from implicit `dynamic` to
`Object` for implementations that don't specify the type since inference
will pick the argument type from the overridden method.
=> Make argument to featureValueOf dynamic

lib/mirror_matchers.dart, lib/src/core_matchers.dart, lib/src/custom_matcher.dart, lib/src/description.dart, lib/src/equals_matcher.dart, lib/src/feature_matcher.dart, lib/src/having_matcher.dart, lib/src/interfaces.dart, lib/src/iterable_matchers.dart, lib/src/map_matchers.dart, lib/src/operator_matchers.dart, lib/src/order_matchers.dart, lib/src/pretty_print.dart, lib/src/string_matchers.dart, lib/src/util.dart, test/custom_matcher_test.dart, test/having_test.dart, test/test_utils.dart
Rolls back some changes which are not trivially safe out of caution so
that the first stable version published will match exactly with the last
published pre-release. These changes will be rolled forward in a feature
release - they are expected to be non-breaking and internal code is
already using this version.
This reverts commits
- 2071cfd84b3ede7277c57d122ef8c74cf0f3c6f0
- 71eeaee1cb8235a47e47bcad9134f744bb1c594a
- 63f1110a657fb5e2dc378db8895fef7b0a13ab30
This does not revert one code change which makes the migration easier
for users using the `same` matcher against nullable types.
- 5d52720b8cdb8ddcc4256950618650e7eabc4176
=> Revert some changes since the latest published

analysis_options.yaml, lib/mirror_matchers.dart, pubspec.yaml, test/core_matchers_test.dart, test/iterable_matchers_test.dart
Fix existing violations of lints:
- `provide_deprecation_message`
- `unnecessary_string_escapes`
=> Move from pedantic to lints package

README.md
The goal is to have some place to link to for common guidance given in
code reviews instead of having to repeat a snippet of explanation each
time.
For now add a single common code review comment. More can be added if
other common comments are identified.
=> Add a Best Practices section to README

.github/workflows/ci.yml, pubspec.yaml
The `test` package has this lower bound, so no real world usage can resolve a newer `matcher` without a 2.18 SDK.
=> Bump min SDK to 2.18.0

CHANGELOG.md, lib/src/error_matchers.dart, pubspec.yaml, test/type_matcher_test.dart
Add `isTypeError` as alternative.
This is the source of the majority of the breakage from the CL to remove `CastError` from the SDK: https://dart-review.googlesource.com/c/sdk/+/258003
=> Stop depending on the deprecated `CastError` type.

CHANGELOG.md, lib/src/type_matcher.dart
The analyzer will surface a diagnostic for misuses like using `..having()` and expecting it to mutate the instance.
=> Annotate TypeMatcher.having with useResult

lib/src/having_matcher.dart
This was made public and marked visible for testing unnecessarily, there are no usages outside of this library.
=> Make FunctionMatcher private

CHANGELOG.md, lib/src/error_matchers.dart, pubspec.yaml, test/type_matcher_test.dart
Prepare for the errors to be removed from the SDK and stop referencing
them entirely. Deprecate the matchers for these errors and change the
types to target the more general `Error` and `TypeError` which will
still catch the same situations.
Move the ignore for same package deprecations to cover the entire test
file.
=> Stop using deprecated errors

lib/src/core_matchers.dart, test/having_test.dart, test/iterable_matchers_test.dart, test/map_matchers_test.dart, test/string_matchers_test.dart
This becomes important when combined with `allOf`.
Consider:
```dart
import 'package:test/test.dart';
main() {
test('contains the right things', () {
expect('abc', allOf(contains('a'), contains('b'), contains('d')));
});
}
```
Before:
```
> dart test
00:02 +0 -1: contains the right things [E]                                                                         
Expected: (contains 'a' and contains 'b' and contains 'd')
Actual: 'abc'
package:test_api      expect
test/a_test.dart 5:5  main.<fn>
```
Notice how it is unclear which of the expectations that failed.
After:
```
> dart test
00:01 +0 -1: contains the right things [E]                                                                         
Expected: (contains 'a' and contains 'b' and contains 'd')
Actual: 'abc'
Which: does not …
```
=> Improve mismatch description of `contains`

test/matcher/prints_test.dart, test/utils_new.dart
These tests were copied from the test repo, and one import was missed.
Fix the test cases for an expanded `contains` mismatch description in #206
=> Fix import and broken tests

lib/src/expect/expect.dart
These were changed to `Object?` from implicit dynamic to satisfy stricter linting in the matcher package, however there are edge cases where changing an argument type from `dynamic` to `Object?` is breaking, so use explicit `dynamic` instead.
The type change can be breaking in cases where it influences inference behavior for one of the arguments. The `dynamic` will not impose a context type on the argument value, while `Object?` does, which changes how generics get inferred.
=> Make the arguments to `expect` dynamic again

lib/expect.dart
When we split `test_api` into smaller libraries I did not include some deprecated or less used APIs through the "focused" library `expect.dart`, while still exporting them through the combined `test_api.dart` library to avoid a backwards incompatibility.
Now that we are moving the APIs to a package we will discontinue, it is not as valuable to try to push migrations between APIs _within_ the package, so re-export them through the `expect.dart` library. This reduces the level of breaking change so that an import update will be all that is needed in every case.
=> Export more APIs through the expect library

CHANGELOG.md, pubspec.yaml, test/expect_async_test.dart, test/matcher/throws_test.dart, test/matcher/throws_type_test.dart
Allow the next breaking release which will remove the exports of
libraries from this package and remove the cyclic dependency.
=> Expand bound for `test_api` dependency

CHANGELOG.md, lib/src/expect/never_called.dart, pubspec.yaml
This will also enable us to enable dartdoc's `missing-code-block-language` warning in Flutter (pkg:matcher is documented together with Flutter).
This also matches the style elsewhere in the repository, e.g. https://github.com/dart-lang/matcher/blob/356e5f68d3484d44b9ef3b814ed95f9de17c7afd/lib/src/custom_matcher.dart#L21
=> Specify language in neverCalled docs for nicer formatting in docs

README.md, lib/src/core_matchers.dart
Add a best practice entry and expand the dartdoc for `predicate` to
mention that the failure messages are not as detailed as `TypeMatcher`,
and that the latter is preferred when the value can fail in more than
one way.
Add a generic argument to the example usage - most cases should prefer
to include a generic.
Cleanup an unnecessary private `typedef` with a single usage.
=> Add more advice away from predicate
