lib/src/core_matchers.dart

@nex3 
Fix #28 replace 'given' with 'actual' in error message
Please review.

close #28 replace 'given' with 'actual' in error message

---

lib/src/core_matchers.dart

Fix custom matcher example

---

test/mirror_matchers_test.dart

Only test mirror matchers on the VM

---

.travis.yml

Stop testing on stable

---

lib/src/pretty_print.dart
test/pretty_print_test.dart

fix: improve prettyPrint output for `Type`

---

test/core_matchers_test.dart
test/iterable_matchers_test.dart
test/numeric_matchers_test.dart
test/string_matchers_test.dart
test/test_utils.dart
test/type_matcher_test.dart

Add a number of tests, one small cleanup

---

CHANGELOG.md
lib/src/error_matchers.dart
test/type_matcher_test.dart

this is a prerequisite to resolving https://github.com/dart-lang/test/issues/904.

add isCastError

---

analysis_options.yaml
lib/mirror_matchers.dart
lib/src/core_matchers.dart
lib/src/custom_matcher.dart
lib/src/description.dart
lib/src/equals_matcher.dart
lib/src/feature_matcher.dart
lib/src/having_matcher.dart
lib/src/iterable_matchers.dart
lib/src/map_matchers.dart
lib/src/numeric_matchers.dart
lib/src/operator_matchers.dart
lib/src/order_matchers.dart
lib/src/string_matchers.dart
lib/src/type_matcher.dart
test/custom_matcher_test.dart
test/pretty_print_test.dart
test/test_utils.dart
test/type_matcher_test.dart

Makes it easier to understand how a class behaves when it is explicit
where it is overriding something from a parent class.
Enable the lint and fix violations.

Add @override annotations

---

CHANGELOG.md
lib/src/numeric_matchers.dart
lib/src/order_matchers.dart
pubspec.yaml
test/numeric_matchers_test.dart
test/order_matchers_test.dart

Don't consider NaN ordered against any number

---

CHANGELOG.md
lib/src/core_matchers.dart

See comments at https://github.com/dart-lang/matcher/issues/98#issuecomment-536785301

Point to isA over TypeMatcher

---

CHANGELOG.md
lib/src/error_matchers.dart
pubspec.yaml

Towards https://github.com/dart-lang/test/issues/1094

Add isAssertionError

---

CHANGELOG.md
lib/src/error_matchers.dart
pubspec.yaml

This reverts commit 98aa43660108af785845f84ffa1fde786d9a0a77.
Rolling this will require coordination with flutter.

Revert "Add isAssertionError (#118)"

---

lib/src/having_matcher.dart

Fixes #122 
Remove redundant type annotation on list literal.

Add missing generic on _FunctionMatcher field

---

lib/src/custom_matcher.dart
lib/src/type_matcher.dart

doc cleanup: - optional `new`s

---

analysis_options.yaml

Also remove errors section: these are caught in CI

analysis_options: remove pedantic duplications

---

CHANGELOG.md
analysis_options.yaml
lib/mirror_matchers.dart
lib/src/core_matchers.dart
lib/src/custom_matcher.dart
lib/src/equals_matcher.dart
lib/src/feature_matcher.dart
lib/src/having_matcher.dart
lib/src/iterable_matchers.dart
lib/src/pretty_print.dart
lib/src/string_matchers.dart
lib/src/type_matcher.dart
lib/src/util.dart
pubspec.yaml
test/custom_matcher_test.dart
test/iterable_matchers_test.dart
test/test_utils.dart
test/type_matcher_test.dart

Analyzer clean, but tests not ran yet.
I did not use the migrator tool as it seemed to get pretty confused by this package and the actual required changes were a lot more minimal than what it wanted to do.
cc @munificent if you want to take a look, I saw that you also had a branch out and I think I did some things differently.

Initial nnbd migration

---

.travis.yml
CHANGELOG.md
lib/src/equals_matcher.dart
lib/src/type_matcher.dart
pubspec.yaml
test/core_matchers_test.dart
test/having_test.dart
test/iterable_matchers_test.dart
test/type_matcher_test.dart

Update version, sdk constraint, changelog, and travis

prep for merge into master

---

CHANGELOG.md
lib/mirror_matchers.dart
lib/src/core_matchers.dart
lib/src/custom_matcher.dart
lib/src/description.dart
lib/src/equals_matcher.dart
lib/src/feature_matcher.dart
lib/src/having_matcher.dart
lib/src/interfaces.dart
lib/src/iterable_matchers.dart
lib/src/map_matchers.dart
lib/src/operator_matchers.dart
lib/src/order_matchers.dart
lib/src/pretty_print.dart
lib/src/string_matchers.dart
lib/src/util.dart
pubspec.yaml
test/custom_matcher_test.dart
test/having_test.dart
test/test_utils.dart

This reverts commit 5aae0d58d334bd329442e832ca5f7cfe5c04dd4e.

Revert "Revert some changes since the latest published (#167)"

---

analysis_options.yaml
lib/src/feature_matcher.dart
lib/src/having_matcher.dart
lib/src/iterable_matchers.dart
lib/src/numeric_matchers.dart
lib/src/operator_matchers.dart
lib/src/order_matchers.dart
lib/src/string_matchers.dart
lib/src/type_matcher.dart
test/custom_matcher_test.dart
test/mirror_matchers_test.dart
test/type_matcher_test.dart

Add explicit dynamic to parameters.
Add some field types in a test file.

Enable and fix lint type_annotate_public_apis

---

CHANGELOG.md
README.md
pubspec.yaml

- prep for publishing 0.12.12
- update the readme file's markdown badges

prep for publishing 0.12.12

---

CHANGELOG.md
lib/src/iterable_matchers.dart
pubspec.yaml
test/iterable_matchers_test.dart

Matches [Iterable]s where exactly one element matches the expected value, and all other elements don't match.

Add containsOnce matcher

---

.github/dependabot.yml
lib/src/type_matcher.dart

blast_repo fixes
